// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	Total     int32       `json:"total"`
	CartItems []*CartItem `json:"cart_items"`
}

type CartItem struct {
	ProductID  string `json:"product_id"`
	ProductSku string `json:"product_sku"`
	Quantity   int32  `json:"quantity"`
}

type CartItemInput struct {
	ProductID  string `json:"product_id"`
	ProductSku string `json:"product_sku"`
	Quantity   int32  `json:"quantity"`
}

type DeleteCartItemInput struct {
	ProductID  string `json:"product_id"`
	ProductSku string `json:"product_sku"`
}

type Mutation struct {
}

type Query struct {
}
