// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	Total     int32       `json:"total"`
	CartItems []*CartItem `json:"cart_items"`
}

type CartItem struct {
	ProductID  string `json:"product_id"`
	ProductSku string `json:"product_sku"`
	Quantity   int32  `json:"quantity"`
}

type CartItemInput struct {
	ProductID  string `json:"product_id"`
	ProductSku string `json:"product_sku"`
	Quantity   int32  `json:"quantity"`
}

type Category struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *string `json:"deleted_at,omitempty"`
}

type CategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type DeleteCartItemInput struct {
	ProductID  string `json:"product_id"`
	ProductSku string `json:"product_sku"`
}

type DeleteCategoryInput struct {
	ID string `json:"id"`
}

type DeleteProductInput struct {
	ID string `json:"id"`
}

type DeleteSubCategoryInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Product struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   string  `json:"description"`
	Summary       string  `json:"summary"`
	Cover         string  `json:"cover"`
	SubCategoryID string  `json:"sub_category_id"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at,omitempty"`
}

type ProductAttribute struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type ProductAttributeInput struct {
	Type string `json:"type"`
}

type ProductInput struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Summary       string `json:"summary"`
	Cover         string `json:"cover"`
	SubCategoryID string `json:"sub_category_id"`
}

type ProductSku struct {
	ID                string          `json:"id"`
	ProductID         string          `json:"product_id"`
	Sku               string          `json:"sku"`
	Price             int32           `json:"price"`
	Quantity          int32           `json:"quantity"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
	DeletedAt         *string         `json:"deleted_at,omitempty"`
	ProductAttributes []*SkuAttribute `json:"product_attributes"`
}

type ProductSkuInput struct {
	ProductID         string    `json:"product_id"`
	Sku               string    `json:"sku"`
	Price             int32     `json:"price"`
	Quantity          int32     `json:"quantity"`
	ProductAttributes []*string `json:"product_attributes"`
}

type Query struct {
}

type SkuAttribute struct {
	ProductSkuID       string `json:"product_sku_id"`
	ProductAttributeID string `json:"product_attribute_id"`
	Value              string `json:"value"`
}

type SkuAttributeInput struct {
	ProductSkuID       string `json:"product_sku_id"`
	ProductAttributeID string `json:"product_attribute_id"`
	Value              string `json:"value"`
}

type SubCategory struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *string `json:"deleted_at,omitempty"`
	CategoryID  string  `json:"category_id"`
}

type SubCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CategoryID  string `json:"category_id"`
}
