// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	DeletedAt   string `json:"deleted_at"`
}

type CategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type DeleteCategoryInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}
