// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteProductInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Product struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   string  `json:"description"`
	Summary       string  `json:"summary"`
	Cover         string  `json:"cover"`
	SubCategoryID string  `json:"sub_category_id"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at,omitempty"`
}

type ProductInput struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Summary       string `json:"summary"`
	Cover         string `json:"cover"`
	SubCategoryID string `json:"sub_category_id"`
}

type Query struct {
}
