// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type ProductAttribute struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

type ProductAttributeInput struct {
	Type string `json:"type"`
}

type ProductSku struct {
	ID                string          `json:"id"`
	ProductID         string          `json:"product_id"`
	Sku               string          `json:"sku"`
	Price             int32           `json:"price"`
	Quantity          int32           `json:"quantity"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
	DeletedAt         *string         `json:"deleted_at,omitempty"`
	ProductAttributes []*SkuAttribute `json:"product_attributes"`
}

type ProductSkuInput struct {
	ProductID string `json:"product_id"`
	Sku       string `json:"sku"`
	Price     int32  `json:"price"`
	Quantity  int32  `json:"quantity"`
}

type Query struct {
}

type SkuAttribute struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type SkuAttributeInput struct {
	ProductSkuID       string `json:"product_sku_id"`
	ProductAttributeID string `json:"product_attribute_id"`
	Value              string `json:"value"`
}
